contentDir = "content"
layoutDir = "layouts"
publishDir = "demo"
baseURL = "https://jeromie.github.io/docs/"
languageCode = "en-us"
title = "My Test Site"
sectionPagesMenu = "main"
theme = "vl"
disableFastRender="true"
