contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
baseURL = "https://jeromie.github.io/public/"
languageCode = "en-us"
title = "My Test Site"
sectionPagesMenu = "main"
theme = "docdock"
